# Generated by Django 4.2.11 on 2024-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=20)),
                ('protocols', models.JSONField(default=list)),
                ('country', models.CharField(max_length=100)),
                ('uptime', models.CharField(max_length=255)),
            ],
        ),
    ]
